name: capreolus
channels:
  - defaults
dependencies:
  - python=3.7
  - pandas
  - spacy<3.0
  - numpy
  - scipy
  - matplotlib
  - cython
  - jupyter
  - jupyterlab
  - h5py==2.10.0
  - pytorch::pytorch>=1.6.0,<=1.8.1
  - pytorch::torchvision
  - cudatoolkit=10.1
  - conda-forge::openjdk>=11,<12
  - pip=21.1.3  # dependency, not package list
  - pip:
    - profane>=0.2.0
    - sqlalchemy~=1.3.19
    - sqlalchemy-utils~=0.36.8
    - psycopg2-binary
    - colorlog>=4.0.2
    - pytrec_eval>=0.5
    - pytest>=3.8.0
    - pyjnius>=1.2.1
    - nltk>=3.4.5
    - pymagnitude>=0.1.143
    - pytest-mock
    - mock
    - pyserini==0.13.0
    - sphinx
    - sphinxcontrib-apidoc
    - recommonmark
    - google-api-python-client
    - oauth2client
    - tensorflow>=2.3,<2.5
    - transformers==4.6.1
    - tensorflow-ranking==0.3.3
    - Pillow
    - beautifulsoup4
    - lxml
    - scispacy<0.4.0
    - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_lg-0.2.4.tar.gz
    - lz4
    - xxhash
    - annoy
    - fasteners
    - smart_open
    - ir_datasets
    - gdown
    - six==1.16.0
