./run_LMD_slurm_annotated_pipeline_PV.sh noneE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMD_noneE_pv ;
sleep 10;
./run_LMD_slurm_annotated_pipeline_PV.sh allE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMD_allE_pv ;
sleep 10;
./run_LMD_slurm_annotated_pipeline_PV.sh domainE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMD_domainE_pv ;
sleep 10;
./run_LMD_slurm_annotated_pipeline_PV.sh specE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMD_specE_pv ;
sleep 300;
./run_LMD_slurm_annotated_pipeline_PV.sh onlyNE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMD_onlyNE_pv ;
sleep 10;
./run_LMD_slurm_annotated_pipeline_PV.sh domainOnlyNE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMD_domainOnlyNE_pv ;
sleep 10;
./run_LMD_slurm_annotated_pipeline_PV.sh specOnlyNE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMD_specOnlyNE_pv ;
sleep 10;