./run_LMDEmb_slurm_annotated_pipeline_PV.sh noneE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMDEmb_noneE_pv ;
sleep 10;
./run_LMDEmb_slurm_annotated_pipeline_PV.sh allE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMDEmb_allE_pv ;
sleep 10;
./run_LMDEmb_slurm_annotated_pipeline_PV.sh domainE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMDEmb_domainE_pv ;
sleep 10;
./run_LMDEmb_slurm_annotated_pipeline_PV.sh specE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMDEmb_specE_pv ;
sleep 300;
./run_LMDEmb_slurm_annotated_pipeline_PV.sh onlyNE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMDEmb_onlyNE_pv ;
sleep 10;
./run_LMDEmb_slurm_annotated_pipeline_PV.sh domainOnlyNE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMDEmb_domainOnlyNE_pv ;
sleep 10;
./run_LMDEmb_slurm_annotated_pipeline_PV.sh specOnlyNE &> /GW/D5data-13/ghazaleh/ranking_outputs/logs_18092020_slurm_jobs/LMDEmb_specOnlyNE_pv ;
sleep 10;